### ISSUE TITLE
App crashes when selecting "Week's stats" on menu

### ISSUE THREAD

**Issue by nemmons** [grimesmea/Capstone-Project#1]
I'm unable to reproduce this now but I did it pretty reliably when i first installed the app (I just forgot to open an issue right away; sorry!). My intuition is that it was crashing when i tried to view the page before i had taken any steps at all, and so there were no stats to display for the week. I'll try to add more detail if i can reproduce it at some later point.

**Comment by grimesmea** [comment]
Thanks for catching this! This issue is resolved, and you were correct that the issue was related to not having any step count history.
